export const levels = [
  {
    level: 1,
    description: "Move the frog to the right using ",
    initialCSS: { display: "flex" },
    targetCSS: { justifyContent: "flex-end" },
    hints: "Use 'justify-content' with 'flex-end'.",
  },
  {
    level: 2,
    description: "Move the frog to the Center using ",
    initialCSS: { display: "flex" },
    targetCSS: { justifyContent: "center" },
    hints: "Use 'justify-content' with 'flex-end'.",
  },
  {
    level: 3,
    description: "Move the frog to the left using ",
    initialCSS: { display: "flex", justifyContent: "flex-end" },
    targetCSS: { justifyContent: "flex-start" },
    hints: "Use 'justify-content' with 'flex-start'.",
  },
  {
    level: 4,
    description: "Move the frog to the left and right using ",
    initialCSS: { display: "flex", justifyContent: "flex-start" },
    targetCSS: { justifyContent: "space-between" },
    hints: "Use 'justify-content' with 'space-between'.",
  },
  {
    level: 5,
    description: "Move the frog to the top right using ",
    initialCSS: { display: "flex", flexDirection: "column-reverse" },
    targetCSS: { flexDirection: "row-reverse" },
    hints: "Use 'flex-direction' with 'column-reverse'.",
  },
  {
    level: 6,
    description: "Move the frog to the bottom using ",
    initialCSS: { display: "flex", justifyContent: "center", alignItems: "flex-start" },
    targetCSS: { alignItems: "flex-end" },
    hints: "Use 'align-items' with 'flex-end'.",
  },
  {
    level: 7,
    description: "Move the frog to the center vertically and horizontally using ",
    initialCSS: { display: "flex", justifyContent: "flex-start", alignItems: "flex-start" },
    targetCSS: { justifyContent: "center", alignItems: "center" },
    hints: "Use both 'justify-content' and 'align-items' to center the frog.",
  },
  {
    level: 8,
    description: "Move the frog to the bottom left using ",
    initialCSS: { display: "flex", justifyContent: "flex-end", alignItems: "flex-start" },
    targetCSS: { justifyContent: "flex-start", alignItems: "flex-end" },
    hints: "Use 'justify-content' with 'flex-start' and 'align-items' with 'flex-end'.",
  },
  {
    level: 9,
    description: "Move the frog evenly spaced from each other using ",
    initialCSS: { display: "flex", justifyContent: "center", gap: "10px" },
    targetCSS: { justifyContent: "space-evenly" },
    hints: "Use 'justify-content' with 'space-evenly'.",
  },
  {
    level: 10,
    description: "Move the frog to the top-right corner using ",
    initialCSS: { display: "flex", flexDirection: "column" },
    targetCSS: { flexDirection: "row-reverse", alignItems: "flex-start" },
    hints: "Use 'flex-direction' with 'row-reverse' and 'align-items' with 'flex-start'.",
  },
  {
    level: 11,
    description: "Move the frog to the top center using ",
    initialCSS: { display: "flex", flexDirection: "column-reverse", alignItems: "center" },
    targetCSS: { alignItems: "center", justifyContent: "flex-start" },
    hints: "Use 'justify-content' with 'flex-start' and 'align-items' with 'center'.",
  },
  {
    level: 12,
    description: "Move the frog to the bottom right using ",
    initialCSS: { display: "flex", flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start" },
    targetCSS: { justifyContent: "flex-end", alignItems: "flex-end" },
    hints: "Use 'justify-content' with 'flex-end' and 'align-items' with 'flex-end'.",
  },
  {
    level: 13,
    description: "Move the frog with space between items using ",
    initialCSS: { display: "flex", justifyContent: "flex-start", gap: "20px" },
    targetCSS: { justifyContent: "space-between" },
    hints: "Use 'justify-content' with 'space-between'.",
  },
  {
    level: 14,
    description: "Move the frog to the middle of a 2D grid using ",
    initialCSS: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gridTemplateRows: "repeat(3, 1fr)" },
    targetCSS: { gridColumn: "2", gridRow: "2" },
    hints: "Use 'grid-column' and 'grid-row' to position the frog in the center of the grid.",
  },
  {
    level: 15,
    description: "Move the frog to the top left in a grid with explicit columns and rows using ",
    initialCSS: { display: "grid", gridTemplateColumns: "200px 200px", gridTemplateRows: "200px 200px" },
    targetCSS: { gridColumn: "1", gridRow: "1" },
    hints: "Use 'grid-column' and 'grid-row' with values for explicit rows and columns.",
  }
];
