export const levels = [
    {
      level: 1,
      description: "Place the item in the center using ",
      initialCSS: { display: "grid" },
      targetCSS: { placeItems: "center" },
      hints: "Use 'place-items' with 'center'.",
    },
    {
      level: 2,
      description: "Align items to the start using ",
      initialCSS: { display: "grid", alignItems: "end" },
      targetCSS: { alignItems: "start" },
      hints: "Use 'align-items' with 'start'.",
    },
    {
      level: 3,
      description: "Distribute items evenly at start using ",
      initialCSS: { display: "grid", justifyContent: "center" },
      targetCSS: { justifyContent: "space-between" },
      hints: "Use 'justify-content' with 'space-between'.",
    },
    {
      level: 4,
      description: "Place items at the bottom right using ",
      initialCSS: { display: "grid", placeItems: "start" },
      targetCSS: { placeItems: "end" },
      hints: "Use 'place-items' with 'end'.",
    },
    {
      level: 5,
      description: "Create a grid with two equal columns using ",
      initialCSS: { display: "grid" },
      targetCSS: { gridTemplateColumns: "1fr 1fr" },
      hints: "Use 'grid-template-columns' with two equal fractional units.",
    },
    {
      level: 6,
      description: "Align items in a grid to the center horizontally and vertically using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr" },
      targetCSS: { placeItems: "center" },
      hints: "Use 'place-items' to center both horizontally and vertically.",
    },
    {
      level: 7,
      description: "Align the first item to the top left and the second to the bottom right using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr", gridTemplateRows: "1fr 1fr" },
      targetCSS: { gridColumn: "1", gridRow: "1", gridColumn: "2", gridRow: "2" },
      hints: "Use 'grid-column' and 'grid-row' to position items specifically.",
    },
    {
      level: 8,
      description: "Distribute items evenly with a gap between them using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr" },
      targetCSS: { justifyItems: "center", gap: "10px" },
      hints: "Use 'justify-items' for horizontal alignment and 'gap' for spacing.",
    },
    {
      level: 9,
      description: "Place items in a 3x3 grid and center them using ",
      initialCSS: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gridTemplateRows: "repeat(3, 1fr)" },
      targetCSS: { placeItems: "center" },
      hints: "Use 'place-items' to center items in the grid.",
    },
    {
      level: 10,
      description: "Create a grid with a row gap of 20px and column gap of 10px using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr" },
      targetCSS: { columnGap: "10px", rowGap: "20px" },
      hints: "Use 'column-gap' and 'row-gap' to add gaps between items.",
    },
    {
      level: 11,
      description: "Place the first item in the middle column of a 3-column grid using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr" },
      targetCSS: { gridColumn: "2" },
      hints: "Use 'grid-column' to position the item in the middle.",
    },
    {
      level: 12,
      description: "Create a 2x2 grid and move the item in the top-right corner to the bottom-left using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr", gridTemplateRows: "1fr 1fr" },
      targetCSS: { gridColumn: "1", gridRow: "2" },
      hints: "Use 'grid-column' and 'grid-row' to move the item.",
    },
    {
      level: 13,
      description: "Move items to the top right using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr" },
      targetCSS: { gridColumn: "2", gridRow: "1" },
      hints: "Use 'grid-column' and 'grid-row' to move the item to the top-right.",
    },
    {
      level: 14,
      description: "Create a 4-column grid with items spanning 2 columns each using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr" },
      targetCSS: { gridColumn: "span 2" },
      hints: "Use 'grid-column' with 'span' to make items span multiple columns.",
    },
    {
      level: 15,
      description: "Align items to the center of the grid horizontally using ",
      initialCSS: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr" },
      targetCSS: { justifyItems: "center" },
      hints: "Use 'justify-items' to center the items horizontally.",
    }
  ];
  